using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using AdminApp.Elements;
using AdminApp.SupportClasses;
using AdminApp.SystemClasses;

namespace AdminApp
{
    /// <summary>
    /// Логика взаимодействия для ChosePersonalRoleView.xaml
    /// </summary>
    public partial class ChosePersonalRoleView : Window
    {
        public ChosePersonalRoleView()
        {
            InitializeComponent();
            var tempItem = new STabItem();
            tempItem.TabItem = new TabItem
            {
                Header = (String)this.FindResource("m_tab_PersonalRole"),
                Name = StaticTypes.PersonalRoleTab,
                Height = 40,
                FontSize = 14
            };
            tempItem.DataGrid = new DataGrid
            {
                Name = StaticTypes.PersonalRoleGrid,
                SelectionMode = DataGridSelectionMode.Single,
                CanUserAddRows = false,
                CanUserDeleteRows = false,
                IsReadOnly = true
            };
            SetInfoToGridPersonalRole(ref tempItem.DataGrid);
            tempItem.TabItem.Content = tempItem.DataGrid;
            tabControl.Items.Add(tempItem.TabItem);
            Style rowStyle = new Style(typeof(DataGridRow));
            rowStyle.Setters.Add(new EventSetter(DataGridRow.MouseDoubleClickEvent,
                new MouseButtonEventHandler(Handlers.RowPersonalRoleView_DoubleClick)));
            tempItem.DataGrid.RowStyle = rowStyle;
            tempItem.DataGrid.AutoGeneratedColumns += (sender, args) =>
            {
                tempItem.DataGrid.Columns[0].Visibility = Visibility.Collapsed;
                SystemSingleton.CurrentSession.SetCaptionToGrid(this, new KeyValuePair<string, STabItem>(StaticTypes.PersonalRoleTab, tempItem));
            };
        }
        public static void SetInfoToGridPersonalRole(ref DataGrid dataGrid)
        {
            try
            {
                SqlConnection con = new SqlConnection(SystemSingleton.Configuration.ConnectionString);
                SqlCommand cmd = new SqlCommand(SqlCommands.SetInfoToGridPersonalRoles, con);
                EnvironmentHelper.SendLogSQL(cmd.CommandText);
                SqlDataAdapter sda = new SqlDataAdapter(cmd);
                DataTable dt = new DataTable("PersonalRoles");
                sda.Fill(dt);
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    dt.Rows[i][5] = (string)SystemSingleton.Configuration.mainWindow.FindResource((string)dt.Rows[i][5]);
                }
                dataGrid.ItemsSource = dt.DefaultView;
            }
            catch (Exception ex)
            {
                EnvironmentHelper.SendErrorDialogBox(ex.Message, "SQL Error", ex.StackTrace);
            }
        }
    }
}
